config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]
  resources :comments
  devise_for :users, path: '', path_names: {sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  ## Override resources values with except command
  resources :portfolios, except: [:show] do
    put :sort, on: :collection
  end
  ## Assign custom route to original route as new path name 
  get 'portfolio/:id', to: 'portfolios#show', as: 'portfolio_show'
  
  get 'about-me', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  
  resources :blogs do
    member do
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'
  
  root to: 'pages#home'

end

app/models/portfolio.rb
class Portfolio < ApplicationRecord
  has_many :technologies

  accepts_nested_attributes_for :technologies,                            allow_destroy: true,
                                reject_if: lambda { |attrs| attrs['name'].blank? }

  include Placeholder
  
  validates_presence_of :title, :body

  mount_uploader :thumb_image, PortfolioUploader
  mount_uploader :main_image, PortfolioUploader

  def self.by_position
    order("position ASC")  
  end

  def self.angular
    where(subtitle: 'Angular')
  end
##Scoping for custom ouputs with our topics
  # def self.angular
  #   where(subtitle: 'Angular')
  # end

  scope :ruby_on_rails_portfolio_item, -> { where(subtitle: 'Ruby on Rails')}
end

app/controllers/portfolios_controller.rb
class PortfoliosController < ApplicationController
  before_action :set_portfolio, only: [:show, :edit, :update, :destroy]
  layout "portfolio"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all
  
  def index
    @portfolios = Portfolio.by_position

##Scoping for custom ouputs with our topics
    # @portfolios = Portfolio.ruby_on_rails_portfolio_item
    # or 
    # @portfolios = Portfolio.angular

  end

  def sort
    params[:order].each do |key, value|
      Portfolio.find(value[:id]).update(position: value[:position])
    end

    render nothing: true
  end

  def new
    @portfolio = Portfolio.new
  end

  def create
    @portfolio = Portfolio.new(portfolio_params)

    respond_to do |format|
      if @portfolio.save
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  def edit  
  end

  def update
    respond_to do |format|
      if @portfolio.update(portfolio_params)
        format.html { redirect_to portfolios_path, notice: 'Portfolio was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def show  
  end

  def destroy
    
    @portfolio.destroy

    respond_to do |format|
      format.html { redirect_to portfolios_url, notice: 'Blog was successfully destroyed.' }
    end
  end

  private
    def set_portfolio
      @portfolio = Portfolio.find(params[:id])
    end

    def portfolio_params
      params.require(:portfolio).permit(:title, 
                                        :subtitle, 
                                        :body, 
                                        :main_image,
                                        :thumb_image,
                                        technologies_attributes: [:id, :name, :_destroy]
                                        )
    end

end

app/helpers/portfolios_helper.rb
module PortfoliosHelper

  def image_generator(height:, width:)
      "https://via.placeholder.com/#{height}x#{width}"
  end

  def portfolio_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
end

app/views/portfolios/_form.html.erb
<%= form_for(@portfolio) do |form| %>
  <% if @portfolio.errors.any? %>
    <% @portfolio.errors.full_messages.each do |message| %>
     <%= alert_generator message %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= form.label :subtitle %>
        <%= form.text_field :subtitle, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label class="btn btn-primary">
          Upload a main image file <%= form.file_field :main_image, style: 'display:none' %>
        </label>  
      </div>

      <div class="form-group">
           <label class="btn btn-primary">
          Upload a thumb image file <%= form.file_field :main_image, style: 'display:none' %>
        </label>
      </div>

    </div>

  
    <div class="col-md-6">
      <div class="form-group">
        <%= form.label :body %>
        <%= form.text_area :body, class: 'form-control', rows: 10 %>
      </div>
    </div>
  </div>

  <hr>
  
  <div class="col-md-12">
    <h2>Technologies Used</h2>
    <div>
      <%= form.fields_for :technologies do |tech| %>
        <%= render 'technology_fields', f: tech %>  
      <% end %>

    <div>
      <%= link_to_add_association 'Add Technology', form, :technologies %>
    </div>

    </div>
    
    <br></br>

    <div class="form-group">
      <%= form.submit 'Save Portfolio Items', class: 'btn btn-primary' %>
    </div>
  </div>
  
<% end %>

app/views/portfolios/_portfolio.html.erb
<div class="col-md-4">
  <div class="card mb-4 shadow-sm" data-id="<%= portfolio.id %>">
  
  <%= image_tag("#{portfolio_img(portfolio.thumb_image, 'thumb')}" , width: '100%') %>

    <div class="card-body">
      <p class="card-text">
        <span><%= link_to portfolio.title, portfolio_show_path(portfolio) %></span>
        <%= portfolio.subtitle %></p>
      <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
          <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/portfolios/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form_control' %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/portfolios/edit.html.erb
<div class="container portfolio-container">
  <h1>Edit this Portfolio</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <%= source_helper("alert alert-warning") %>

    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">
      <!-- partial for data collection manual implementation -->
      <%= render partial: 'portfolio', collection: @portfolios %>
    </div>
  </div>
</div>

app/views/portfolios/new.html.erb
<div class="container portfolio-form">
  <h1>Create a New Portfolio</h1>

  <%= render 'form', portfolio_item: @portfolio_item %>
</div>

app/views/portfolios/show.html.erb
<div class="container portfolio-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag("#{portfolio_img(@portfolio.main_image, 'main')}" , width: '100%') %>
    </div>
    <div class="col-md-5">
      <h1><%= @portfolio.title %></h1>

      <em><%= @portfolio.subtitle %></em>

      <p><%= @portfolio.body %></p>

      <h3>Technologies Used:</h3>

      <% @portfolio.technologies.each do |tech| %>
        <p><%= tech.name %></p>
      <% end %>
      
      <% if logged_in?(:site_admin) %>
        <div class="col-md-12">
          <%= link_to 'Edit Item', edit_portfolio_path(@portfolio), class: 'btn btn-warning' %>
        </div>
      <% end %>
    </div>
  </div>
</div>